name = "globeflags2"
main = "src/index.ts"
compatibility_date = "2024-03-21"

[assets]
directory = "./dist"
include = ["**/*"]

[build]
command = "npm run build"
watch_dir = "src"

[triggers]
crons = []

[vars]
NODE_ENV = "production"

[env.production]
name = "globeflags2"
route = "globeflags.info/*"
zone_id = ""  # Hier muss die Zone-ID eingefügt werden

[env.production.vars]
NODE_ENV = "production"

[env.development]
name = "globeflags2-dev"
route = "dev.globeflags.info/*"
zone_id = ""  # Hier muss die Zone-ID eingefügt werden

[env.development.vars]
NODE_ENV = "development" 