name = "globeflags2"
main = "dist/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Konfigurationen für statische Assets
[site]
bucket = "./dist"

[build]
command = "npm run build"

# Umgebungsvariablen festlegen
[vars]
NODE_ENV = "production"

# Route-Konfigurationen
[[routes]]
pattern = "globeflags.info/*"
# Zone-ID wird automatisch von Cloudflare zugewiesen

[[routes]]
pattern = "globeflags2.chomeles.workers.dev/*"

# Worker-Platzierung optimieren
[placement]
mode = "smart"

# Trigger-Ereignisse definieren
[triggers]
crons = []

# Bindings konfigurieren für die KV-Assets
[kv_namespaces]
binding = "ASSETS" 